### ISSUE TITLE
employee problem

### ISSUE THREAD

**Issue by fyb9527** [WABM/Espresso#5]
1.添加员工信息里面出生日期和入职日期两个选填其实是必填的，而真正选填的电话没有标出来。
2.添加员工时不填电话和账号密码也可以添加，而点击修改电话却又变成必填项了。
3.账户名和密码真的是选填项么？
4.删除了员工之后仍然能够修改那个员工的信息

**Comment by MainasuK** [comment]
@Mrforget 😄
